# Generated by Django 4.1.3 on 2022-12-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_perros_delete_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
