# Generated by Django 4.1.3 on 2022-12-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0004_autos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='autos',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.AlterField(
            model_name='autos',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
    ]
